### ISSUE TITLE
Totem of holding 

### ISSUE THREAD

**Issue by Ctfurlani** [lucidobservor/floramancer-modpack#5]
Sorry, can't get my items. I also carried it before, because i had no clue how to open it. Maybe carrying it messed up something

**Comment by lucidobservor** [comment]
...yep, that's an issue. Turns out moving a Totem of Holding with Carry On breaks it. I've just added the totem to the Carry On blacklist, and the pack release containing that fix should be up within the hour.

For your particular problem, go into Mod Options -> Quark -> Oddities, click the wrench next to "Totem of Holding," and check "Allow Anyone to Collect." In my local testing, this worked to retrieve items from a totem which had been moved with Carry On.

Thank you for bringing this to my attention!

(Commit: aa09534bf190c7216ea3fb1b3471d65d80b02c7e)

**Comment by Ctfurlani** [comment]
Thank you once again
