### ISSUE TITLE
Quark is still on the version from December, 20 versions behind

### ISSUE THREAD

**Issue by Goldenlion5648** [lucidobservor/floramancer-modpack#8]
Is there a reason that quark has not been updated in so long?

**Comment by lucidobservor** [comment]
For the recent 1.3.0 release, I updated most of the mods in the pack. However, in updating Quark in particular, I ran into some issues (though I don't remember now what they were). Rather than push the release back again, I left Quark and AutoRegLib at the same version I was previously using. 

I'll leave this issue open as a reminder to update Quark at some point, but I can't promise any sort of ETA on when I'll get around to that.

**Comment by lucidobservor** [comment]
Updated in the upcoming 1.4.0 release
